server:
  port: 9091

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anil-cmd/ProperyFilesForProjects
          clone-on-start: true
management:
  security:
    enabled: false